name: HIL

on:
  workflow_dispatch:

jobs:
  hil-test:
    name: STM32F401RE HIL Test

    runs-on:
      - self-hosted
      - Windows
      - X64

    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Python
        shell: powershell
        run: |
          py --version

      - name: Verify CMake
        shell: powershell
        run: |
          cmake --version

      - name: Verify Ninja
        shell: powershell
        run: |
          ninja --version

      - name: Verify STM32 Programmer CLI
        shell: powershell
        run: |
          STM32_Programmer_CLI.exe --version

      - name: Verify COM8
        shell: powershell
        run: |
          $ports = [System.IO.Ports.SerialPort]::GetPortNames()

          Write-Host "Available serial ports:"
          $ports

          if ($ports -notcontains "COM8") {
              Write-Error "COM8 was not detected."
              exit 1
          }

      - name: Run HIL
        shell: powershell
        run: |
          py tests\hil\run_hil.py
