name: HIL

on:
  workflow_dispatch:

jobs:
  hil-test:
    name: STM32F401RE HIL Test

    runs-on:
      - self-hosted
      - Windows
      - X64

    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Descargar Python portable
        shell: powershell
        run: |
          $pythonVersion = "3.10.11"
          $pythonUrl = "https://www.python.org/ftp/python/$pythonVersion/python-$pythonVersion-embed-amd64.zip"
          $pythonZip = "$env:RUNNER_TEMP\python.zip"
          $pythonDir = "$env:RUNNER_TEMP\python"

          Write-Host "Descargando Python $pythonVersion..."

          Invoke-WebRequest `
            -Uri $pythonUrl `
            -OutFile $pythonZip

          if (Test-Path $pythonDir) {
              Remove-Item $pythonDir -Recurse -Force
          }

          New-Item -ItemType Directory -Path $pythonDir | Out-Null

          Expand-Archive `
            -Path $pythonZip `
            -DestinationPath $pythonDir `
            -Force

          Write-Host "Python portable instalado en:"
          Write-Host $pythonDir

      - name: Preparar pip para Python portable
        shell: powershell
        run: |
          $pythonDir = "$env:RUNNER_TEMP\python"
          $pythonExe = "$pythonDir\python.exe"

          Write-Host "Python portable:"
          & $pythonExe --version

          Invoke-WebRequest `
            -Uri "https://bootstrap.pypa.io/get-pip.py" `
            -OutFile "$env:RUNNER_TEMP\get-pip.py"

          & $pythonExe "$env:RUNNER_TEMP\get-pip.py"

      - name: Instalar PySerial
        shell: powershell
        run: |
          $pythonExe = "$env:RUNNER_TEMP\python\python.exe"

          & $pythonExe -m pip install --no-warn-script-location pyserial

      - name: Verificar Python
        shell: powershell
        run: |
          $pythonExe = "$env:RUNNER_TEMP\python\python.exe"

          & $pythonExe --version

          & $pythonExe -c "import serial; print('PySerial:', serial.__version__)"

      - name: Verify CMake
        shell: powershell
        run: |
          cmake --version

      - name: Verify Ninja
        shell: powershell
        run: |
          ninja --version

      - name: Verify STM32 Programmer CLI
        shell: powershell
        run: |
          STM32_Programmer_CLI.exe --version

      - name: Verify COM8
        shell: powershell
        run: |
          $ports = [System.IO.Ports.SerialPort]::GetPortNames()

          Write-Host "Available serial ports:"
          $ports

          if ($ports -notcontains "COM8") {
              Write-Error "COM8 was not detected."
              exit 1
          }

      - name: Run HIL
        shell: powershell
        run: |
          $pythonExe = "$env:RUNNER_TEMP\python\python.exe"

          & $pythonExe tests\hil\run_hil.py
